### ISSUE TITLE
statuser is in permanent NaN on debug builds

### ISSUE THREAD

**Issue by chutten** [chutten/statuser#6]
If the background hang reporter isn't on, then the code gets stuck thinking that 'NaN' would be a good thing to show all the time.

Maybe default it to EVENTLOOP_UI_ACTIVITY_EXP_MS when BHR isn't available? (( what should we do if telemetry is disabled, too? ))

**Comment by Uberi** [comment]
Fixed in #5 - now the badge shows up as a ?, with a message in the panel explaining why the stats aren't available.
