### ISSUE TITLE
Optionally play a sound when incrementing the badge

### ISSUE THREAD

**Issue by mikeconley** [chutten/statuser#9]
I've noticed that the count reported in the badge will increase when I'm not paying attention. It might be useful to play a short sound when the badge count increases, in order to get my attention.

This should probably be disabled by default, but enable-able from a checkbox in the panel.

**Comment by chutten** [comment]
The most important part of any feature is the ability to TURN IT OFF.

**Comment by mikeconley** [comment]
Certainly. Let's definitely not make this on by default, and make it very simple in the panel to shut off once enabled.

**Comment by Uberi** [comment]
Implemented in #10, with other improvements in #15.
